// This file is autogenerated, do not edit directly.

import {getApiBase, api, filterQuery} from '../defaults'

import {ApiTokenResponse} from '../schemas/ApiTokenResponse'
import {ApiTokenCreatedResponse} from '../schemas/ApiTokenCreatedResponse'
import {ApiTokenCreateRequest} from '../schemas/ApiTokenCreateRequest'
import {StatusMessage} from '../schemas/StatusMessage'

export const listTokens = async (): Promise<ApiTokenResponse[]> => {
  return await api.get<ApiTokenResponse[]>(`/api_tokens/`)
}
export const createToken = async (content: ApiTokenCreateRequest): Promise<ApiTokenCreatedResponse> => {
  return await api.post<ApiTokenCreatedResponse>(`/api_tokens/`, content)
}
export const deleteToken = async (token_id: number): Promise<StatusMessage> => {
  return await api.delete<StatusMessage>(`/api_tokens/${token_id}`)
}
