// This file is autogenerated, do not edit directly.

import {getApiBase, api} from '../defaults'

import {StatusMessage} from '../schemas/StatusMessage'
import {AuthFields} from '../schemas/AuthFields'

export const login = async (content: AuthFields): Promise<StatusMessage> => {
  return await api.post<StatusMessage>(`/auth/login`, content)
}
export const logout = async (): Promise<StatusMessage> => {
  return await api.post<StatusMessage>(`/auth/logout`)
}
