// This file is autogenerated, do not edit directly.

import {mande} from 'mande'

import {getApiBase} from '../defaults'

import {StatusMessage} from '../schemas/StatusMessage'
import {AuthFields} from '../schemas/AuthFields'

export const login = async (content: AuthFields): Promise<StatusMessage> => {
  const api = mande(getApiBase() + `/auth/login`)
  return await api.post<StatusMessage>(content)
}
export const logout = async (): Promise<StatusMessage> => {
  const api = mande(getApiBase() + `/auth/logout`)
  return await api.post<StatusMessage>('')
}
