// This file is autogenerated, do not edit directly.

import {getApiBase, api} from '../defaults'

import {CommentResponse} from '../schemas/CommentResponse'
import {CommentUpdate} from '../schemas/CommentUpdate'
import {StatusMessage} from '../schemas/StatusMessage'

export const updateComment = async (comment_id: number, content: CommentUpdate): Promise<CommentResponse> => {
  return await api.put<CommentResponse>(`/comments/${comment_id}`, content)
}
export const deleteComment = async (comment_id: number): Promise<StatusMessage> => {
  return await api.delete<StatusMessage>(`/comments/${comment_id}`)
}
