// This file is autogenerated, do not edit directly.

import {getApiBase, api} from '../defaults'

import {DocumentWithRecordsCount} from '../schemas/DocumentWithRecordsCount'
import {Document} from '../schemas/Document'
import {Body_create_doc_document__post} from '../schemas/Body_create_doc_document__post'
import {StatusMessage} from '../schemas/StatusMessage'
import {DocumentRecordListResponse} from '../schemas/DocumentRecordListResponse'
import {MemorySubstitution} from '../schemas/MemorySubstitution'
import {GlossaryRecordSchema} from '../schemas/GlossaryRecordSchema'
import {DocumentRecordUpdateResponse} from '../schemas/DocumentRecordUpdateResponse'
import {DocumentRecordUpdate} from '../schemas/DocumentRecordUpdate'
import {DocTranslationMemory} from '../schemas/DocTranslationMemory'
import {DocTranslationMemoryUpdate} from '../schemas/DocTranslationMemoryUpdate'
import {TranslationMemoryListResponse} from '../schemas/TranslationMemoryListResponse'
import {TranslationMemoryListSimilarResponse} from '../schemas/TranslationMemoryListSimilarResponse'
import {DocGlossary} from '../schemas/DocGlossary'
import {DocGlossaryUpdate} from '../schemas/DocGlossaryUpdate'
import {DocumentProcessingSettings} from '../schemas/DocumentProcessingSettings'

export const getDocs = async (): Promise<DocumentWithRecordsCount[]> => {
  return await api.get<DocumentWithRecordsCount[]>(`/document/`)
}
export const createDoc = async (data: Body_create_doc_document__post): Promise<Document> => {
  const formData = new FormData()
  formData.append('file', data.file)
  return await api.post<Document>(`/document/`, formData)
}
export const getDoc = async (doc_id: number): Promise<DocumentWithRecordsCount> => {
  return await api.get<DocumentWithRecordsCount>(`/document/${doc_id}`)
}
export const deleteDoc = async (doc_id: number): Promise<StatusMessage> => {
  return await api.delete<StatusMessage>(`/document/${doc_id}`)
}
export const getDocRecords = async (doc_id: number, page?: number | null, source?: string | null, target?: string | null): Promise<DocumentRecordListResponse> => {
  return await api.get<DocumentRecordListResponse>(`/document/${doc_id}/records`, {query: {page, source, target}})
}
export const getRecordSubstitutions = async (doc_id: number, record_id: number): Promise<MemorySubstitution[]> => {
  return await api.get<MemorySubstitution[]>(`/document/${doc_id}/records/${record_id}/substitutions`)
}
export const getRecordGlossaryRecords = async (doc_id: number, record_id: number): Promise<GlossaryRecordSchema[]> => {
  return await api.get<GlossaryRecordSchema[]>(`/document/${doc_id}/records/${record_id}/glossary_records`)
}
export const updateDocRecord = async (record_id: number, content: DocumentRecordUpdate): Promise<DocumentRecordUpdateResponse> => {
  return await api.put<DocumentRecordUpdateResponse>(`/document/record/${record_id}`, content)
}
export const getTranslationMemories = async (doc_id: number): Promise<DocTranslationMemory[]> => {
  return await api.get<DocTranslationMemory[]>(`/document/${doc_id}/memories`)
}
export const setTranslationMemories = async (doc_id: number, content: DocTranslationMemoryUpdate): Promise<StatusMessage> => {
  return await api.post<StatusMessage>(`/document/${doc_id}/memories`, content)
}
export const searchTmExact = async (doc_id: number, source: string): Promise<TranslationMemoryListResponse> => {
  return await api.get<TranslationMemoryListResponse>(`/document/${doc_id}/tm/exact`, {query: {source}})
}
export const searchTmSimilar = async (doc_id: number, source: string): Promise<TranslationMemoryListSimilarResponse> => {
  return await api.get<TranslationMemoryListSimilarResponse>(`/document/${doc_id}/tm/similar`, {query: {source}})
}
export const getGlossaries = async (doc_id: number): Promise<DocGlossary[]> => {
  return await api.get<DocGlossary[]>(`/document/${doc_id}/glossaries`)
}
export const setGlossaries = async (doc_id: number, content: DocGlossaryUpdate): Promise<StatusMessage> => {
  return await api.post<StatusMessage>(`/document/${doc_id}/glossaries`, content)
}
export const processDoc = async (doc_id: number, content: DocumentProcessingSettings): Promise<StatusMessage> => {
  return await api.post<StatusMessage>(`/document/${doc_id}/process`, content)
}
export const getDownloadDocLink = (doc_id: number): string => {
  return getApiBase() + `/document/${doc_id}/download`
}
