// This file is autogenerated, do not edit directly.

import {getApiBase, api} from '../defaults'

import {DocumentWithRecordsCount} from '../schemas/DocumentWithRecordsCount'
import {Document} from '../schemas/Document'
import {Body_create_doc_document__post} from '../schemas/Body_create_doc_document__post'
import {StatusMessage} from '../schemas/StatusMessage'
import {DocumentRecord} from '../schemas/DocumentRecord'
import {MemorySubstitution} from '../schemas/MemorySubstitution'
import {DocumentRecordUpdate} from '../schemas/DocumentRecordUpdate'
import {DocTranslationMemory} from '../schemas/DocTranslationMemory'
import {DocTranslationMemoryUpdate} from '../schemas/DocTranslationMemoryUpdate'
import {DocumentProcessingSettings} from '../schemas/DocumentProcessingSettings'

export const getDocs = async (): Promise<DocumentWithRecordsCount[]> => {
  return await api.get<DocumentWithRecordsCount[]>(`/document/`)
}
export const createDoc = async (data: Body_create_doc_document__post): Promise<Document> => {
  const formData = new FormData()
  formData.append('file', data.file)
  return await api.post<Document>(`/document/`, formData)
}
export const getDoc = async (doc_id: number): Promise<DocumentWithRecordsCount> => {
  return await api.get<DocumentWithRecordsCount>(`/document/${doc_id}`)
}
export const deleteDoc = async (doc_id: number): Promise<StatusMessage> => {
  return await api.delete<StatusMessage>(`/document/${doc_id}`)
}
export const getDocRecords = async (doc_id: number, page?: number | null): Promise<DocumentRecord[]> => {
  return await api.get<DocumentRecord[]>(`/document/${doc_id}/records`, {query: {page}})
}
export const getRecordSubstitutions = async (doc_id: number, record_id: number): Promise<MemorySubstitution[]> => {
  return await api.get<MemorySubstitution[]>(`/document/${doc_id}/records/${record_id}/substitutions`)
}
export const updateDocRecord = async (record_id: number, content: DocumentRecordUpdate): Promise<DocumentRecord> => {
  return await api.put<DocumentRecord>(`/document/record/${record_id}`, content)
}
export const getTranslationMemories = async (doc_id: number): Promise<DocTranslationMemory[]> => {
  return await api.get<DocTranslationMemory[]>(`/document/${doc_id}/memories`)
}
export const setTranslationMemories = async (doc_id: number, content: DocTranslationMemoryUpdate): Promise<StatusMessage> => {
  return await api.post<StatusMessage>(`/document/${doc_id}/memories`, content)
}
export const processDoc = async (doc_id: number, content: DocumentProcessingSettings): Promise<StatusMessage> => {
  return await api.post<StatusMessage>(`/document/${doc_id}/process`, content)
}
export const getDownloadDocLink = (doc_id: number): string => {
  return getApiBase() + `/document/${doc_id}/download`
}
