// This file is autogenerated, do not edit directly.

import {getApiBase, api} from '../defaults'

import {GlossaryDocumentResponse} from '../schemas/GlossaryDocumentResponse'
import {GlossaryLoadFileResponse} from '../schemas/GlossaryLoadFileResponse'
import {Body_create_glossary_doc_from_file_glossary_load_file_post} from '../schemas/Body_create_glossary_doc_from_file_glossary_load_file_post'

export const listGlossaryDocs = async (): Promise<GlossaryDocumentResponse[]> => {
  return await api.get<GlossaryDocumentResponse[]>(`/glossary/docs`)
}
export const retrieveGlossaryDoc = async (glossary_doc_id: number): Promise<GlossaryDocumentResponse> => {
  return await api.get<GlossaryDocumentResponse>(`/glossary/docs/${glossary_doc_id}`)
}
export const createGlossaryDocFromFile = async (data: Body_create_glossary_doc_from_file_glossary_load_file_post): Promise<GlossaryLoadFileResponse> => {
  const formData = new FormData()
  formData.append('file', data.file)
  return await api.post<GlossaryLoadFileResponse>(`/glossary/load_file`, formData)
}
