// This file is autogenerated, do not edit directly.

import {getApiBase, api} from '../defaults'

import {DocumentRecordUpdateResponse} from '../schemas/DocumentRecordUpdateResponse'
import {DocumentRecordUpdate} from '../schemas/DocumentRecordUpdate'
import {CommentResponse} from '../schemas/CommentResponse'
import {CommentCreate} from '../schemas/CommentCreate'
import {MemorySubstitution} from '../schemas/MemorySubstitution'
import {DocumentRecordHistoryListResponse} from '../schemas/DocumentRecordHistoryListResponse'
import {GlossaryRecordSchema} from '../schemas/GlossaryRecordSchema'

export const updateDocRecord = async (record_id: number, content: DocumentRecordUpdate): Promise<DocumentRecordUpdateResponse> => {
  return await api.put<DocumentRecordUpdateResponse>(`/records/${record_id}`, content)
}
export const getComments = async (record_id: number): Promise<CommentResponse[]> => {
  return await api.get<CommentResponse[]>(`/records/${record_id}/comments`)
}
export const createComment = async (record_id: number, content: CommentCreate): Promise<CommentResponse> => {
  return await api.post<CommentResponse>(`/records/${record_id}/comments`, content)
}
export const getRecordSubstitutions = async (record_id: number): Promise<MemorySubstitution[]> => {
  return await api.get<MemorySubstitution[]>(`/records/${record_id}/substitutions`)
}
export const getSegmentHistory = async (record_id: number): Promise<DocumentRecordHistoryListResponse> => {
  return await api.get<DocumentRecordHistoryListResponse>(`/records/${record_id}/history`)
}
export const getRecordGlossaryRecords = async (record_id: number): Promise<GlossaryRecordSchema[]> => {
  return await api.get<GlossaryRecordSchema[]>(`/records/${record_id}/glossary_records`)
}
