// This file is autogenerated, do not edit directly.

import {getApiBase, api} from '../defaults'

import {TranslationMemory} from '../schemas/TranslationMemory'
import {Body_create_translation_memory_translation_memory__post} from '../schemas/Body_create_translation_memory_translation_memory__post'
import {TranslationMemoryWithRecordsCount} from '../schemas/TranslationMemoryWithRecordsCount'
import {StatusMessage} from '../schemas/StatusMessage'
import {TranslationMemoryRecord} from '../schemas/TranslationMemoryRecord'

export const getTranslationMemories = async (): Promise<TranslationMemory[]> => {
  return await api.get<TranslationMemory[]>(`/translation_memory/`)
}
export const createTranslationMemory = async (data: Body_create_translation_memory_translation_memory__post): Promise<TranslationMemory> => {
  const formData = new FormData()
  formData.append('file', data.file)
  return await api.post<TranslationMemory>(`/translation_memory/`, formData)
}
export const getTranslationMemory = async (tm_id: number): Promise<TranslationMemoryWithRecordsCount> => {
  return await api.get<TranslationMemoryWithRecordsCount>(`/translation_memory/${tm_id}`)
}
export const deleteTranslationMemory = async (tm_id: number): Promise<StatusMessage> => {
  return await api.delete<StatusMessage>(`/translation_memory/${tm_id}`)
}
export const getTranslationMemoryRecords = async (tm_id: number, page?: number | null): Promise<TranslationMemoryRecord[]> => {
  return await api.get<TranslationMemoryRecord[]>(`/translation_memory/${tm_id}/records`, {query: {page}})
}
