// This file is autogenerated, do not edit directly.

import {defaults, mande} from 'mande'

import {getApiBase} from '../defaults'

import {TmxFile} from '../schemas/TmxFile'
import {Body_create_tmx_tmx__post} from '../schemas/Body_create_tmx_tmx__post'
import {TmxFileWithRecords} from '../schemas/TmxFileWithRecords'
import {StatusMessage} from '../schemas/StatusMessage'

export const getTmxs = async (): Promise<TmxFile[]> => {
  const api = mande(getApiBase() + `/tmx/`)
  return await api.get<TmxFile[]>('')
}
export const createTmx = async (data: Body_create_tmx_tmx__post): Promise<TmxFile> => {
  const formData = new FormData()
  formData.append('file', data.file)
  const defaultHeaders = defaults.headers
  try {
    const api = mande(getApiBase() + `/tmx/`)
    defaults.headers = {}
    return await api.post<TmxFile>('', formData)
  } catch (error: any) {
    throw error
  } finally {
    defaults.headers = defaultHeaders
  }
}
export const getTmx = async (tmx_id: number): Promise<TmxFileWithRecords> => {
  const api = mande(getApiBase() + `/tmx/${tmx_id}`)
  return await api.get<TmxFileWithRecords>('')
}
export const deleteTmx = async (tmx_id: number): Promise<StatusMessage> => {
  const api = mande(getApiBase() + `/tmx/${tmx_id}`)
  return await api.delete<StatusMessage>('')
}
