// This file is autogenerated, do not edit directly.

import {mande} from 'mande'

import {getApiBase} from '../defaults'

import {TmxFile} from '../schemas/TmxFile'
import {Body_create_tmx_tmx__post} from '../schemas/Body_create_tmx_tmx__post'
import {TmxFileWithRecordsCount} from '../schemas/TmxFileWithRecordsCount'
import {StatusMessage} from '../schemas/StatusMessage'
import {TmxFileRecord} from '../schemas/TmxFileRecord'

export const getTmxs = async (): Promise<TmxFile[]> => {
  const api = mande(getApiBase() + `/tmx/`)
  return await api.get<TmxFile[]>('')
}
export const createTmx = async (data: Body_create_tmx_tmx__post): Promise<TmxFile> => {
  const formData = new FormData()
  formData.append('file', data.file)
  const api = mande(getApiBase() + `/tmx/`)
  return await api.post<TmxFile>('', formData)
}
export const getTmx = async (tmx_id: number): Promise<TmxFileWithRecordsCount> => {
  const api = mande(getApiBase() + `/tmx/${tmx_id}`)
  return await api.get<TmxFileWithRecordsCount>('')
}
export const deleteTmx = async (tmx_id: number): Promise<StatusMessage> => {
  const api = mande(getApiBase() + `/tmx/${tmx_id}`)
  return await api.delete<StatusMessage>('')
}
export const getTmxRecords = async (tmx_id: number, page?: number | null): Promise<TmxFileRecord[]> => {
  const api = mande(getApiBase() + `/tmx/${tmx_id}/records`)
  return await api.get<TmxFileRecord[]>('', {query: {page}})
}
