// This file is autogenerated, do not edit directly.

import {getApiBase, api} from '../defaults'

import {RegistrationTokenResponse} from '../schemas/RegistrationTokenResponse'
import {StatusMessage} from '../schemas/StatusMessage'

export const listTokens = async (): Promise<RegistrationTokenResponse[]> => {
  return await api.get<RegistrationTokenResponse[]>(`/registration_tokens/`)
}
export const createToken = async (): Promise<RegistrationTokenResponse> => {
  return await api.post<RegistrationTokenResponse>(`/registration_tokens/`)
}
export const deleteToken = async (token_id: number): Promise<StatusMessage> => {
  return await api.delete<StatusMessage>(`/registration_tokens/${token_id}`)
}
