// This file is autogenerated, do not edit directly.

import {getApiBase, api} from '../defaults'

import {User} from '../schemas/User'
import {UserToCreate} from '../schemas/UserToCreate'
import {StatusMessage} from '../schemas/StatusMessage'
import {UserFields} from '../schemas/UserFields'

export const getUsers = async (): Promise<User[]> => {
  return await api.get<User[]>(`/users/`)
}
export const createUser = async (content: UserToCreate): Promise<User> => {
  return await api.post<User>(`/users/`, content)
}
export const updateUser = async (user_id: number, content: UserFields): Promise<StatusMessage> => {
  return await api.post<StatusMessage>(`/users/${user_id}`, content)
}
