// This file is autogenerated, do not edit directly.

import {getApiBase, api, filterQuery} from '../defaults'

import {User} from '../schemas/User'

export const getCurrentUser = async (): Promise<User> => {
  return await api.get<User>(`/user/`)
}
