// This file is autogenerated, do not edit directly.

import {mande} from 'mande'

import {getApiBase} from '../defaults'

import {User} from '../schemas/User'

export const getCurrentUser = async (): Promise<User> => {
  const api = mande(getApiBase() + `/user/`)
  return await api.get<User>('')
}
