[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

[tool.coverage.run]
omit = ["**/tests/*"]

[tool.ruff]
line-length = 88
exclude = [".venv", "alembic"]

[tool.ruff.lint.isort]
default-section = "third-party"

