// This file is autogenerated, do not edit directly.

export interface ApiTokenResponse {
  id: number
  name: string
  user_id: number
  created_by: number
  created_at: string
  expires_at: string | null
  last_used_at: string | null
}
