// This file is autogenerated, do not edit directly.

import {ShortUser} from './ShortUser'

export interface CommentResponse {
  id: number
  text: string
  updated_at: string
  record_id: number
  created_by_user: ShortUser
}
