// This file is autogenerated, do not edit directly.

import {DocumentWithRecordsCount} from './DocumentWithRecordsCount'

export interface DetailedProjectResponse {
  id: number
  created_at: string
  updated_at: string
  name: string
  created_by: number
  documents: DocumentWithRecordsCount[]
  approved_records_count: number
  total_records_count: number
  approved_words_count: number
  total_words_count: number
}
