// This file is autogenerated, do not edit directly.

import {TranslationMemory} from './TranslationMemory'
import {TmMode} from './TmMode'

export interface DocTranslationMemory {
  document_id: number
  memory: TranslationMemory
  mode: TmMode
}
