// This file is autogenerated, do not edit directly.

import {TranslationMemoryWithMode} from './TranslationMemoryWithMode'

export interface DocTranslationMemoryUpdate {
  memories: TranslationMemoryWithMode[]
}
