// This file is autogenerated, do not edit directly.

import {DocumentStatus} from './DocumentStatus'

export interface Document {
  id: number
  name: string
  status: DocumentStatus
  created_by: number
  type: string
  project_id: number | null
}
