// This file is autogenerated, do not edit directly.

import {ShortUser} from './ShortUser'
import {DocumentRecordHistoryChangeType} from './DocumentRecordHistoryChangeType'

export interface DocumentRecordHistory {
  id: number
  diff: string
  author: ShortUser | null
  timestamp: string
  change_type: DocumentRecordHistoryChangeType
}
