// This file is autogenerated, do not edit directly.

import {DocumentRecord} from './DocumentRecord'

export interface DocumentRecordListResponse {
  records: DocumentRecord[]
  page: number
  total_records: number
}
