// This file is autogenerated, do not edit directly.

import {DocumentRecordExtended} from './DocumentRecordExtended'

export interface DocumentRecordListResponse {
  records: DocumentRecordExtended[]
  page: number
  total_records: number
}
