// This file is autogenerated, do not edit directly.

import {MachineTranslationSettings} from './MachineTranslationSettings'
import {TranslationMemoryUsage} from './TranslationMemoryUsage'

export interface DocumentProcessingSettings {
  substitute_numbers: boolean
  machine_translation_settings: MachineTranslationSettings | null
  tm_ids: number[]
  tm_usage: TranslationMemoryUsage
  similarity_threshold?: number
}
