// This file is autogenerated, do not edit directly.

import {DocumentStatus} from './DocumentStatus'

export interface DocumentWithRecordsCount {
  id: number
  name: string
  status: DocumentStatus
  created_by: number
  type: string
  approved_records_count: number
  records_count: number
}
