// This file is autogenerated, do not edit directly.

import {DocumentStatus} from './DocumentStatus'

export interface DocumentWithRecordsCount {
  id: number
  name: string
  status: DocumentStatus
  created_by: number
  type: string
  project_id: number | null
  approved_records_count: number
  total_records_count: number
  approved_word_count: number
  total_word_count: number
}
