// This file is autogenerated, do not edit directly.

import {LlmTranslatorSettings} from './LlmTranslatorSettings'
import {YandexTranslatorSettings} from './YandexTranslatorSettings'

export interface DocumentProcessingSettings {
  machine_translation_settings: LlmTranslatorSettings | YandexTranslatorSettings | null
  similarity_threshold?: number
}
