// This file is autogenerated, do not edit directly.

import {RecordSource} from './RecordSource'

export interface DocumentRecord {
  id: number
  source: string
  target: string
  approved: boolean
  repetitions_count: number
  has_comments: boolean
  translation_src: RecordSource | null
}
