// This file is autogenerated, do not edit directly.

import {DocumentRecordHistory} from './DocumentRecordHistory'

export interface DocumentRecordHistoryListResponse {
  history: DocumentRecordHistory[]
}
