// This file is autogenerated, do not edit directly.

import {ShortUser} from './ShortUser'

export interface GlossaryResponse {
  id: number
  created_at: string
  updated_at: string
  processing_status: string
  upload_time: string
  created_by_user: ShortUser
  name: string
  records_count: number
}
