// This file is autogenerated, do not edit directly.

export interface GlossaryRecordSchema {
  id: number
  created_at: string
  updated_at: string
  created_by: number
  comment: string | null
  source: string
  target: string
  glossary_id: number
}
