// This file is autogenerated, do not edit directly.

export interface GlossaryResponse {
  id: number
  created_at: string
  updated_at: string
  processing_status: string
  upload_time: string
  created_by: number
  name: string
}
