// This file is autogenerated, do not edit directly.

import {GlossaryRecordSchema} from './GlossaryRecordSchema'

export interface GlossaryRecordResponse {
  records: GlossaryRecordSchema[]
  total_rows: number
}
