// This file is autogenerated, do not edit directly.

export interface GlossaryDocumentResponse {
  id: number
  created_at: string
  updated_at: string
  processing_status: string
  upload_time: string
  user_id: number
}
