// This file is autogenerated, do not edit directly.

export type P = 'glossary:read' | 'glossary:upload' | 'glossary:download' | 'glossary:create' | 'glossary:update' | 'glossary:delete' | 'glossary_record:create' | 'tm:read' | 'tm:create' | 'tm:delete' | 'tm:upload' | 'tm:download' | 'record:read' | 'record:edit' | 'document:read' | 'document:create' | 'document:delete' | 'document:update' | 'document:download' | 'document:process' | 'project:read' | 'project:create' | 'project:update' | 'project:delete' | 'project:manage_resources' | 'comment:create' | 'comment:manage' | 'user:manage'
