// This file is autogenerated, do not edit directly.

import {ShortUser} from './ShortUser'

export interface ProjectResponseWithWordsCount {
  id: number
  created_at: string
  updated_at: string
  name: string
  user_id: number
  user: ShortUser
  approved_segments_count: number
  total_segments_count: number
  approved_words_count: number
  total_words_count: number
}
