// This file is autogenerated, do not edit directly.

import {ShortUser} from './ShortUser'

export interface ProjectResponse {
  id: number
  created_at: string
  updated_at: string
  name: string
  user_id: number
  user: ShortUser
}
