// This file is autogenerated, do not edit directly.

import {TranslationMemory} from './TranslationMemory'
import {TmMode} from './TmMode'

export interface ProjectTm {
  memory: TranslationMemory
  mode: TmMode
}
