// This file is autogenerated, do not edit directly.

import {ShortUser} from './ShortUser'
import {SegmentHistoryChangeType} from './SegmentHistoryChangeType'

export interface SegmentHistory {
  id: number
  diff: string | null
  author: ShortUser | null
  timestamp: string
  change_type: SegmentHistoryChangeType
}
