// This file is autogenerated, do not edit directly.

export type SegmentHistoryChangeType = 'initial_import' | 'machine_translation' | 'tm_substitution' | 'glossary_substitution' | 'repetition' | 'manual_edit'
