// This file is autogenerated, do not edit directly.

import {TmxFileRecord} from './TmxFileRecord'

export interface TmxFileWithRecords {
  id: number
  name: string
  created_by: number
  records: TmxFileRecord[]
}
