// This file is autogenerated, do not edit directly.

import {TranslationMemoryRecordWithSimilarity} from './TranslationMemoryRecordWithSimilarity'

export interface TranslationMemoryListSimilarResponse {
  records: TranslationMemoryRecordWithSimilarity[]
  page: number
  total_records: number
}
