// This file is autogenerated, do not edit directly.

import {TranslationMemoryRecord} from './TranslationMemoryRecord'

export interface TranslationMemoryListResponse {
  records: TranslationMemoryRecord[]
  page: number
  total_records: number
}
