// This file is autogenerated, do not edit directly.

import {UserRole} from './UserRole'

export interface User {
  email: string
  username: string
  role: UserRole
  disabled: boolean
  id: number
}
