// This file is autogenerated, do not edit directly.

import {UserRole} from './UserRole'

export interface UserToCreate {
  username: string
  email: string
  role: UserRole
  disabled: boolean
  password: string
}
