// This file is autogenerated, do not edit directly.

import {UserRole} from './UserRole'
import {P} from './P'

export interface UserWithPermissions {
  email: string
  username: string
  role: UserRole
  disabled: boolean
  id: number
  permissions: P[]
}
