// This file is autogenerated, do not edit directly.

import {MachineTranslationSettings} from './MachineTranslationSettings'

export interface XliffProcessingSettings {
  substitute_numbers: boolean
  use_machine_translation: boolean
  machine_translation_settings: MachineTranslationSettings | null
}
