// This file is autogenerated, do not edit directly.

import {XliffFileRecord} from './XliffFileRecord'

export interface XliffFileWithRecords {
  id: number
  name: string
  records: XliffFileRecord[]
}
