// This file is autogenerated, do not edit directly.

import {DocumentStatus} from './DocumentStatus'

export interface XliffFileWithRecordsCount {
  id: number
  name: string
  status: DocumentStatus
  created_by: number
  records_count: number
}
