// This file is autogenerated, do not edit directly.

import {MachineTranslationSettings} from './MachineTranslationSettings'
import {TmxUsage} from './TmxUsage'

export interface XliffProcessingSettings {
  substitute_numbers: boolean
  use_machine_translation: boolean
  machine_translation_settings: MachineTranslationSettings | null
  tmx_file_ids: number[]
  tmx_usage: TmxUsage
}
