// This file is autogenerated, do not edit directly.

import {DocumentStatus} from './DocumentStatus'
import {XliffFileRecord} from './XliffFileRecord'

export interface XliffFileWithRecords {
  id: number
  name: string
  status: DocumentStatus
  records: XliffFileRecord[]
}
